version: "3.8"

services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1 # To ensure logs are visible in real-time